### ISSUE TITLE
high cpu usage with no client connected Ubuntu server 16.04

### ISSUE THREAD

**Issue by iw5ejm** [simonyiszk/openwebrx#109]
Is normal that the csdr process is running also with no client connected and using cpu as if there was clients?
![schermata 2018-02-08 alle 23 48 25](https://user-images.githubusercontent.com/30696288/36002476-997ed0dc-0d2a-11e8-8253-1ae0efe1dbd9.png)

**Comment by ha7ilm** [comment]
Could you please tell the full command with `top -c`? If it is `csdr fft_cc, then it is okay.

**Comment by iw5ejm** [comment]
![schermata 2018-02-09 alle 09 19 53](https://user-images.githubusercontent.com/30696288/36018026-73a0eca6-0d7a-11e8-9aed-390a7229fa64.png)

**Comment by ha7ilm** [comment]
This is normal. The `csdr fft_cc` process runs always, even if there is no user connected. This is which generates the waterfall diagram. It was easier to implement this way (although starting/stopping this process could be done).

**Comment by iw5ejm** [comment]
Ok so to try stopping the fft_cc process I have to look in csdr.py file, DSP class right?

**Comment by ha7ilm** [comment]
Yes.

**Comment by ha7ilm** [comment]
You should look for spectrum thread.
