### ISSUE TITLE
404 message Invalid path

### ISSUE THREAD

**Issue by Jonny-Johnson** [simonyiszk/openwebrx#113]
Hi there,

tried to install the software on a Raspi 3 with Rasbian Stretch in the Lite version. My current guess is, maybe the Lite is causing the issue (although it doesn't make sense to me), so I will try the regular version.

After starting I get this error when trying to access <<<local ip>>>:8073.
In my browser: 404 with "Message: Invalid path. Error code explanation: 404 = Nothing matches the given URI."
In my SSH console: 
`client 0x16a20f8: CS_THREAD_FINISHED, client_goto_source = 2, errno = 32192.168.178.21 - - [28/Apr/2018 15:52:03] code 404, message Invalid path.
192.168.178.21 - - [28/Apr/2018 15:52:03] "GET / HTTP/1.1" 404 -
192.168.178.21 - - [28/Apr/2018 15:52:15] code 404, message Invalid path.
192.168.178.21 - - [28/Apr/2018 15:52:15] "GET / HTTP/1.1" 404 -
192.168.178.21 - - [28/Apr/2018 15:52:19] code 404, message Invalid path.
192.168.178.21 - - [28/Apr/2018 15:52:19] "GET / HTTP/1.1" 404 -
`

Here is the full console output:
`pi@raspberrypi:~ $ ./openwebrx/openwebrx.py

OpenWebRX - Open Source SDR Web App for Everyone!  | for license see LICENSE file in the package
_________________________________________________________________________________________________

Author contact info:    Andras Retzler, HA7ILM <randras@sdr.hu>

[openwebrx-main] Configuration script not specified. I will use: "config_webrx.py"
[openwebrx-main] nmux_bufsize = 602112, nmux_bufcnt = 84
[openwebrx-main] Started rtl_thread: rtl_sdr -s 2400000 -f 144250000 -p 0 -g 5 -| nmux --bufsize 602112 --bufcnt 84 --port 4951 --address 127.0.0.1
[openwebrx-main] Waiting for I/Q server to start...
nmux: listening on 127.0.0.1:4951
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
[openwebrx-main] I/Q server started.
nmux: pthread_create() done, clients now: 1
client 0x16a20f8: started!
[openwebrx-main] Starting watchdog threads.
[openwebrx-main] Starting spectrum thread.
[openwebrx-spectrum] Spectrum thread initialized successfully.
 [openwebrx-main] Starting HTTP server.
[openwebrx-dsp-plugin:csdr] Command = nc -v 127.0.0.1 4951 | csdr convert_u8_f | csdr fft_cc 4096 2867 | csdr logaveragepower_cf -70 4096 93 | csdr fft_exchange_sides_ff 4096 | csdr compress_fft_adpcm_f_u8 4096
[openwebrx-spectrum] Spectrum thread started.
nmux: pthread_create() done, clients now: 2
Connection to 127.0.0.1 4951 port [tcp/*] succeeded!
client 0x16a21e0: started!
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Sampling at 2400000 S/s.
Tuned to 144250000 Hz.
Tuner gain set to 3.70 dB.
Reading samples in async mode...
client 0x16a20f8: CS_THREAD_FINISHED, client_goto_source = 2, errno = 32192.168.178.21 - - [28/Apr/2018 15:52:03] code 404, message Invalid path.
192.168.178.21 - - [28/Apr/2018 15:52:03] "GET / HTTP/1.1" 404 -
192.168.178.21 - - [28/Apr/2018 15:52:15] code 404, message Invalid path.
192.168.178.21 - - [28/Apr/2018 15:52:15] "GET / HTTP/1.1" 404 -
192.168.178.21 - - [28/Apr/2018 15:52:19] code 404, message Invalid path.
192.168.178.21 - - [28/Apr/2018 15:52:19] "GET / HTTP/1.1" 404 -`

This tutorial (https://www.hamspirit.de/8028/openwebrx-auf-einem-raspberry-pi/) called for the openwebrx folder to be in a src folder where other shit got downloaded before. I didn't do it like that but I guess since the startup didn't show any error this might not be the issue?

Thanks for any help

Best Regards
Jonny

**Comment by ha7ilm** [comment]
Run `openwebrx.py` from the `openwebrx` folder (so please `cd` into it first).
