### ISSUE TITLE
Minor thing ..change text colour on WebGUI Configuration

### ISSUE THREAD

**Issue by npaisnel** [simonyiszk/openwebrx#121]
Just wondering how to change the text colour for stuff like:
 below 
I have added my own background photo but the text colour is wrong for the photo, so text is 'hidden'
receiver_name="[EGJJ]"
receiver_location="Jersey Airport"
receiver_qra="EGJJ"
receiver_asl=10
receiver_ant="Half Wave Dipole"
receiver_device="NooElec Smart RTL-SDR"
receiver_admin="example@example.com"
receiver_gps=(49.204319,-2.192970)

**Comment by ha7ilm** [comment]
In `index,wrx` or `openwebrx.css`.

**Comment by npaisnel** [comment]
thanks
