### ISSUE TITLE
Support for GrOsmoSDR

### ISSUE THREAD

**Issue by zarya** [simonyiszk/openwebrx#13]
Is there any support planned for http://sdr.osmocom.org/trac/wiki/GrOsmoSDR ?

**Comment by ha7ilm** [comment]
Done.  Please provide feedback if it works for you.
https://github.com/simonyiszk/openwebrx/wiki/Using-GrOsmoSDR-as-signal-source

**Comment by nickoe** [comment]
This seems to work very well for me. Using the funcube dongle as the receiver.

**Comment by ha7ilm** [comment]
Great! Thanks for testing.
