### ISSUE TITLE
outgoing sound equalizer

### ISSUE THREAD

**Issue by 30rj076** [simonyiszk/openwebrx#131]
Hello everyone, I have a web server with openwebrx and a raspberry pi 3. I would like to know if it is possible to equalize the outgoing sound in the web interface, since I find it very shrill and sharp ... could it be modified in any way?

**Comment by ha7ilm** [comment]
From the web interface, it's not possible.

You might edit the code of CSDR and manually design a new FIR filter for `deemphasis_nfm_ff` (which applies to NFM only).
