### ISSUE TITLE
Create script to start

### ISSUE THREAD

**Issue by 30rj076** [simonyiszk/openwebrx#133]
Hi guys, I need your help;

I have an OpenWebRx server running with a Raspberry Pi 3B. Sometimes I have power cuts and I restart the Raspberry and internet router with the assignment of a new public IP. I have already installed the DNS service program of www.noip.com to redirect.

I want to create a script at startup with the following commands;

1st) After starting the Raspberry, wait 5 minutes for the router to synchronize the internet service with the new public IP assigned at the time.

2nd) After spending those 5 minutes, run the NOIP program to update the DNS service with the current IP.

3rd) Wait 1 minute and execute the openwebrx.py file on the LX TERMINAL window

Can anyone write me the lines of code for this purpose? Thank you.

**Comment by ha7ilm** [comment]
https://github.com/simonyiszk/openwebrx/wiki/Running-OpenWebRX-on-system-startup
