### ISSUE TITLE
Openwebrx issue with Airspy HF+

### ISSUE THREAD

**Issue by HFATL** [simonyiszk/openwebrx#140]
Hello all,

I'm just trying to config the openwebrx with the AirspyHF+ in my raspberry Pi.
I’ve followed this guide: https://blog.sdr.hu/2015/06/30/quick-setup-openwebrx.html
And this one: https://github.com/simonyiszk/openwebrx/wiki/Using-OpenWebRX-with-an-AirSpyHF
 
However I get this error:

OpenWebRX - Open Source SDR Web App for Everyone!  | for license see LICENSE file in the package
_________________________________________________________________________________________________

Author contact info:    Andras Retzler, HA7ILM <randras@sdr.hu>

[openwebrx-main] Configuration script not specified. I will use: "config_webrx.py"
[openwebrx-main] nmux_bufsize = 192512, nmux_bufcnt = 260
[openwebrx-main] Started rtl_thread: /home/pi/openwebrx/airspyhf/tools/src/airspyhf_rx.c -f 144250000 -r /dev/stdout| nmux --bufsize 192512 --bufcnt 260 --port 4951 --address 127.0.0.1
[openwebrx-main] Waiting for I/Q server to start...
/bin/sh: 1: /home/pi/openwebrx/airspyhf/tools/src/airspyhf_rx.c: Permission denied
nmux: listening on 127.0.0.1:4951
nmux: (main thread/for) end input stream, exiting.

Any help please?

Thank you

**Comment by ha7ilm** [comment]
This is not OpenWebRX related. You should check the guide for `airspyhf_rx`  on compiling and installing it. 

That is sure that you should not try to run the C file as a shell script.
