### ISSUE TITLE
FM squelch

### ISSUE THREAD

**Issue by enthru** [simonyiszk/openwebrx#16]
Hello.
Thanks for websdr opensource alternative.
Its possible to add squelch function? Looks like only this feature needed for everyday VHF/UHF FM use :)
Sorry for my english, R0AFJ, 73!

**Comment by ha7ilm** [comment]
Working on it.

**Comment by nickoe** [comment]
Shouldn't this be closed, in the latest master there is a squelch slider with an auto button too.

**Comment by ha7ilm** [comment]
You're right!
