### ISSUE TITLE
Possible to link to RX with frequency and mode in an URL

### ISSUE THREAD

**Issue by sm3sgp** [simonyiszk/openwebrx#21]
I would be nice to be able to directly via the URL be able to point to an RX including frequency and mode.
Example:
http://openwebrx.host.com/?tune=3638.5lsb

Additionally be able to copy the URL with frequency and mode when listening to a station on an openwebrx.

**Comment by ha7ilm** [comment]
Already implemented in the dev branch:

https://github.com/simonyiszk/openwebrx/tree/dev

> OpenWebRX now supports URLs like: http://localhost:8073/#freq=145555000,mod=usb

(I'm sorry about that I'm not progressing fast with releasing new versions. Many improvements are already in the dev branch, for example a NEON-optimized DDC.)

**Comment by sm3sgp** [comment]
Ok, great! I will probably add some more "issues". I will check the dev branch before I post something.

**Comment by ha7ilm** [comment]
No problem, feel free to add more issues / bugs / ideas!
