### ISSUE TITLE
Use http://localhost:8073/#freq=9240000,mod=usb, get 10.077,11

### ISSUE THREAD

**Issue by DE8MSH** [simonyiszk/openwebrx#28]
Hi.

If I set the frequency with "http://localhost:8073/#freq=9240000,mod=usb" the receiver label says "10.077,11 MHz". This seems to be a small bug in getting the freq by url.

**Comment by ha7ilm** [comment]
Thanks for reporting it. Fixed with commit e11ccbfb1f5920ca44e3fe00c9baa00ee2c93e41. Reopen if you still have issues.
