### ISSUE TITLE
Add support for WFM

### ISSUE THREAD

**Issue by misterdevil** [simonyiszk/openwebrx#54]
Hi when i try to run openwebrx for receiver on FM radio in my area I got some problem. In my area frequency for FM radio is between 87-108 MHz. I try to set center freq on 87 Mhz and so on but when I choose FM modulation it just noise that I got. but when i choose AM modulation it can get some radio broadcast when it  supposed to be FM broadcast in this frequency although the quality is bad. 

config I use :
# ==== DSP/RX settings ====
dsp_plugin="csdr"
fft_fps=9
fft_size=4096
fft_voverlap_factor=0.3 #If it is above 0, multiple FFTs will be used for creating a line on the diagram.
samp_rate = 2400000
center_freq = 87700000
rf_gain = 0 #in dB. For an RTL-SDR, rf_gain=0 will set the tuner to auto gain mode, else it will be in manual gain mode.
ppm = 0

audio_compression="adpcm" #valid values: "adpcm", "none"
fft_compression="adpcm" #valid values: "adpcm", "none"

start_rtl_thread=True

I use RTL-sdr 820T2 device. 
I try to modify gain, sample rate, etc but nothing work on FM modulation, I just got noise only. but it work on AM modulation although its bad quality.

Do we need to add some modulation or something else to enable receive an FM broadcast on frequency 87 Mhz  ? or there is another fault ? 
Thanks for the help.

**Comment by ha7ilm** [comment]
OpenWebRX currently only supports NFM (Narrow-band FM). 

Broadcast stations are WFM (Wide FM), which means that the frequency deviation (and thus the bandwidth) is much higher. OpenWebRX currently uses an IF bandwidth of 10..12 kHz, so it needs to be modified to add that capability.

**Comment by misterdevil** [comment]
now I know, thanks for answer andras. anyway can you give me a reference to modified so it can work on wideFM ?

**Comment by FoxxMD** [comment]
@ha7ilm did you ever get this working?

**Comment by ha7ilm** [comment]
Yes, I did, but for a very old version, and it was only a partial solution (GUI support was incomplete, e.g. the filter bandwidths shown were incorrect).

**Comment by FoxxMD** [comment]
Do you have a branch with that code? I would be happy to work on this feature.

**Comment by ziotibia81** [comment]
@ha7ilm Could you share your code? I would be very happy to looking into it and learning something new. :-D
