### ISSUE TITLE
Cannot Email Developer

### ISSUE THREAD

**Issue by BT-Justice** [simonyiszk/openwebrx#6]
I have been trying to send an email to randras@sdr.hu but I keep getting the email returned as...

SMTP error from remote server after RCPT command:
host: mail.sdr.hu
Administrative prohibition

Please fix this.  Get a free Outlook.com email account or something please.

**Comment by ha7ilm** [comment]
Hi BT-Justice, 

Thanks for reporting that, I'll look after it!
(Yesterday I've been happiply using that address, maybe something happened at my provider...)

Until that, you can contact me at:

retzlerandras@gmail.com

Best regards,

Andras

**Comment by BT-Justice** [comment]
Thanks.  Just sent you an email.

**Comment by ha7ilm** [comment]
I've tested my e-mail address (randras@sdr.hu), and it should work now!

**Comment by BT-Justice** [comment]
"randras@sdr.hu":
SMTP error from remote server after RCPT command:
host: mail.sdr.hu
Administrative prohibition

**Comment by ha7ilm** [comment]
Interesting. I managed to receive mail from both outlook.com and Gmail accounts yesterday, and there was no such error. 

As a workaround, can still mail me at the other address.

**Comment by BT-Justice** [comment]
I use GMX.com for my email so maybe your server blocks it for some reason.
