### ISSUE TITLE
help my

### ISSUE THREAD

**Issue by markusgraj** [simonyiszk/openwebrx#64]
Hello who will help me configure it all I rtl 2838u, I can not configure this thank Marek
step bay step

**Comment by ha7ilm** [comment]
Hi,

Can you tell more about the error messages you get?

**Comment by markusgraj** [comment]
sorry,the receiver is inactive due to internal error

**Comment by ha7ilm** [comment]
And on the terminal?

**Comment by markusgraj** [comment]
vitrtual box

**Comment by ha7ilm** [comment]
I mean, the console output of the `openwebrx` command.

**Comment by markusgraj** [comment]
give me the email address of your

**Comment by markusgraj** [comment]
I will give you the data and check yourself

**Comment by markusgraj** [comment]
I sent you a message

**Comment by ha7ilm** [comment]
Moved to e-mail.

**Comment by markusgraj** [comment]
hi Do I have to have installed python 2.7 on ubuntu


________________________________
Od: András Retzler <notifications@github.com>
Wysłane: 8 lutego 2017 09:03
Do: simonyiszk/openwebrx
DW: markusgraj; Author
Temat: Re: [simonyiszk/openwebrx] help my (#64)


Moved to e-mail.

**Comment by ha7ilm** [comment]
Yes, you need at least python 2.7.6. I didn't try with older versions.

**Comment by markusgraj** [comment]
Thank you for your help, everything works, tell me how to change the picture in openweb

________________________________
Od: András Retzler <notifications@github.com>
Wysłane: 8 lutego 2017 17:51
Do: simonyiszk/openwebrx
DW: markusgraj; Author
Temat: Re: [simonyiszk/openwebrx] help my (#64)


Yes, you need at least python 2.7.6. I didn't try with older versions.

**Comment by ha7ilm** [comment]
Replace `htdocs/gfx/openwebrx-top-photo.jpg` with your own.

**Comment by markusgraj** [comment]
thank you very much
________________________________
Od: András Retzler <notifications@github.com>
Wysłane: 10 lutego 2017 13:48
Do: simonyiszk/openwebrx
DW: markusgraj; Author
Temat: Re: [simonyiszk/openwebrx] help my (#64)


Replace htdocs/gfx/openwebrx-top-photo.jpg with your own.

**Comment by markusgraj** [comment]
Hi I'm part of the problem server cpu 100% I have something set wrong, it is a win 10, cpu intel pentium 2.6, 4GB RAM thank you for helping Marek


________________________________
Od: András Retzler <notifications@github.com>
Wysłane: 10 lutego 2017 13:48
Do: simonyiszk/openwebrx
DW: markusgraj; Author
Temat: Re: [simonyiszk/openwebrx] help my (#64)


Replace htdocs/gfx/openwebrx-top-photo.jpg with your own.

**Comment by ha7ilm** [comment]
I think it is possible on a single core Intel Pentium that you use up all the CPU time. You can try these tips though:

https://github.com/simonyiszk/openwebrx/wiki/Optimizing-OpenWebRX-for-speed

**Comment by markusgraj** [comment]
HI  of my question, my sdr is shifted by 2 khz as you can to correct the thank Marek

________________________________
Od: András Retzler <notifications@github.com>
Wysłane: 12 lutego 2017 15:52
Do: simonyiszk/openwebrx
DW: markusgraj; Author
Temat: Re: [simonyiszk/openwebrx] help my (#64)


I think it is possible on a single core Intel Pentium that you use up all the CPU time. You can try these tips though:

https://github.com/simonyiszk/openwebrx/wiki/Optimizing-OpenWebRX-for-speed

[https://avatars0.githubusercontent.com/u/5983248?v=3&s=400]<https://github.com/simonyiszk/openwebrx/wiki/Optimizing-OpenWebRX-for-speed>

Optimizing OpenWebRX for speed - GitHub<https://github.com/simonyiszk/openwebrx/wiki/Optimizing-OpenWebRX-for-speed>
github.com
DSP CPU usage can be fine-tuned in plugins/dsp/csdr/plugin.py: you can set transition bandwidths higher (thus degrade filter performance by decreasing the length of ...

**Comment by ha7ilm** [comment]
https://github.com/simonyiszk/openwebrx/wiki/Correcting-the-frequency-offset

**Comment by ha7ilm** [comment]
...or you can also do: 

    shown_center_freq = center_freq - 2000

**Comment by markusgraj** [comment]
Thank you for your help


________________________________
Od: András Retzler <notifications@github.com>
Wysłane: 13 lutego 2017 08:43
Do: simonyiszk/openwebrx
DW: markusgraj; Author
Temat: Re: [simonyiszk/openwebrx] help my (#64)


...or you can also do:

shown_center_freq = center_freq - 2000

**Comment by markusgraj** [comment]
Hello I have a question I signed up on the website with you, if I can rearrange all the data on the program (ha5kfu at my 2os073) and the rest?

________________________________
Od: András Retzler <notifications@github.com>
Wysłane: 13 lutego 2017 08:43
Do: simonyiszk/openwebrx
DW: markusgraj; Author
Temat: Re: [simonyiszk/openwebrx] help my (#64)


...or you can also do:

shown_center_freq = center_freq - 2000

**Comment by ha7ilm** [comment]
You can do anything with the web interface, as long as you comply with the [license](https://github.com/simonyiszk/openwebrx/blob/master/LICENSE.txt).

You can replace the OpenWebRX and the HA5KFU logo if you want.

To comply with the AGPL license, you need to distribute the modified source code to those who you give access to your receiver.

**Comment by markusgraj** [comment]
hi what program you can edit the file WRX


________________________________
Od: András Retzler <notifications@github.com>
Wysłane: 13 lutego 2017 08:43
Do: simonyiszk/openwebrx
DW: markusgraj; Author
Temat: Re: [simonyiszk/openwebrx] help my (#64)


...or you can also do:

shown_center_freq = center_freq - 2000

**Comment by ha7ilm** [comment]
Any text editor, like `gedit`, `nano`, `vim`.
