### ISSUE TITLE
Wiki error / update

### ISSUE THREAD

**Issue by zanco** [simonyiszk/openwebrx#69]
In the wiki, the setup for multiple instances of openwebrx contains an error. 

https://github.com/simonyiszk/openwebrx/wiki/Setting-up-multiple-receivers-on-the-same-machine tells to edit the config_rtl.py but there is no such file. The file which needs editing (in my opinion) is the config_webrx.py

**Comment by ha7ilm** [comment]
Thanks! Fixed!
