### ISSUE TITLE
Disable listing sdr on sdr.hu?

### ISSUE THREAD

**Issue by Hiermur** [simonyiszk/openwebrx#75]
Hello,

i have registered my sdr and i have received the key. All is ok.

When i unwanted listing at sdr.hu, i set sdrhu_public_listing to False.

I also removed the sdrhu_key.

My sdr is still listet.

How can disable temporary listing my sdr?

**Comment by ha7ilm** [comment]
Listing will be automatically removed once your receiver is unavailable at the same URL for an hour. 

Contact me if it is still listed after that.

**Comment by Hiermur** [comment]
Ok. Thats the reason my SDR is permanent listet and ignoring my settings.

While testing the SDR, it would be whishfull to set the SDR temporary disable from public listening.

73

**Comment by ha7ilm** [comment]
If you change the port number in the config, it will be unlisted in
approximately 5 minutes.

2017-04-06 22:51 GMT+02:00 Hiermur <notifications@github.com>:

**Comment by Hiermur** [comment]
Ok. Thank you.
