### ISSUE TITLE
Frequency error

### ISSUE THREAD

**Issue by daniel5457h** [simonyiszk/openwebrx#95]
Hi,

With the last version, I've a frequency display error around 105kHz @ 27MHz in the waterfall and demodulator (mostly, everywhere). I've tested with an older version on the same computer and all is working ok. Played around the ppm adjustment and no luck.

Receiver is an RTL-SDR.

Thanks,
Daniel.

**Comment by ha7ilm** [comment]
Was it solved?

**Comment by daniel5457h** [comment]
Hi,

Yes, my mistake, I put the default frequency where the mixer lo frequency should be.

By the way, my receiver is not longer listed in sdr.hu... The keys and the flag are correctly set... Was this a change from your part on the sdr.hu policy or a bug/mistake that needs investigation?

Thanks,
Daniel.

**Comment by ha7ilm** [comment]
> By the way, my receiver is not longer listed in sdr.hu... The keys and the flag are correctly set... Was this a change from your part on the sdr.hu policy or a bug/mistake that needs investigation?

No. Which receiver is that? What happens if you run `python sdrhu.py`?

**Comment by daniel5457h** [comment]
I get a nice
[openwebrx-sdrhu] Update succeeded! (Your receiver is soon getting
listed on sdr.hu!)
but no listing.
The receiver is somewhat "EA3HRU blah blah", address http://z-ha-dum.dy
ndns.org:8080 It's accessible from the outside.
Best regards,
	Daniel.El mié, 25-10-2017 a las 06:47 +0000, András Retzler escribió:

**Comment by ha7ilm** [comment]
Yes, it looks okay. Did you modify the settings recently?

**Comment by ha7ilm** [comment]
Your avatar is too large. Make it under 10.000 bytes.
